name: ose-course-scientific-computing

channels:
- defaults
- conda-forge

dependencies:
- black
- flake8
- ipython
- ipykernel
- jupyter
- jupyter_contrib_nbextensions
- jupyter_nbextensions_configurator
- nbsphinx
- nb_black
- pip
- restructuredtext_lint
- pip:
    - black-nb
    - flake8-nb
    - sphinx_rtd_theme
    - sphinxcontrib-bibtex>=2.0.0
